### Quickstart: Compare runs, choose a model, and deploy it to a REST API

In this quickstart, you will:

- Run a hyperparameter sweep on a training script

- Compare the results of the runs in the MLflow UI

- Choose the best run and register it as a model

- Deploy the model to a REST API

- Build a container image suitable for deployment to a cloud platform

In [5]:
import keras
import numpy
import pandas 
from sklearn.metrics import mean_squared_error
from sklearn.model_selection import train_test_split
# from hyperot import STATUS_OK,Trails,fmin,hp,tpe

import mlflow
# from mlflow.model import infer_signature

In [2]:
import pandas as pd

In [3]:
## load the dataset
data=pd.read_csv(
    "https://raw.githubusercontent.com/mlflow/mlflow/master/tests/datasets/winequality-white.csv",
    sep=";",
)
data

      fixed acidity  volatile acidity  citric acid  ...  sulphates  alcohol  quality
0               7.0              0.27         0.36  ...       0.45      8.8        6
1               6.3              0.30         0.34  ...       0.49      9.5        6
2               8.1              0.28         0.40  ...       0.44     10.1        6
3               7.2              0.23         0.32  ...       0.40      9.9        6
4               7.2              0.23         0.32  ...       0.40      9.9        6
...             ...               ...          ...  ...        ...      ...      ...
4893            6.2              0.21         0.29  ...       0.50     11.2        6
4894            6.6              0.32         0.36  ...       0.46      9.6        5
4895            6.5              0.24         0.19  ...       0.46      9.4        6
4896            5.5              0.29         0.30  ...       0.38     12.8        7
4897            6.0              0.21         0.38  ...       0.32     11.8        6

[4898 rows x 12 columns]

In [6]:
train,test = train_test_split(data , test_size=0.25 , random_state=42)

In [8]:
train[['quality']].values.ravel()

array([6, 6, 5, ..., 6, 6, 8])

In [9]:
train_x = train.drop(['quality'],axis = 1).values
train_y = train[['quality']].values.ravel()

In [ ]:
print(train_x)
print(train_y)

[[ 6.3   0.25  0.22 ...  3.16  0.5  10.5 ]
 [ 7.8   0.3   0.29 ...  3.16  0.38  9.  ]
 [ 7.4   0.38  0.27 ...  3.17  0.43 10.  ]
 ...
 [ 7.6   0.27  0.52 ...  3.02  0.53 11.4 ]
 [ 6.3   0.24  0.29 ...  3.17  0.38 10.6 ]
 [ 8.1   0.27  0.35 ...  3.22  0.63 10.4 ]] [6 6 5 ... 6 6 8]